language: ruby
cache: bundler
# only run CI-builds on master branch
branches:
  only:
  - develop
rvm:
  - 2.7.2
# set execution permission on our build script
before_script:
 - chmod +x ./.cibuild
# path to our build script. 
# Travis will run `bundle install` by default before running our script
script: ./.cibuild

notifications:
  email: false